# Generated by Django 4.2.3 on 2023-08-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('user', 'user')], default='Superuser', max_length=50),
        ),
    ]
