# Generated by Django 4.2.3 on 2023-08-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
