# Generated by Django 4.2.3 on 2023-08-09 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appy', '0003_remove_customuser_id_alter_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_datetime', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='usermodelpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermodelpermission',
            name='model',
        ),
        migrations.RemoveField(
            model_name='usermodelpermission',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='bookshop',
            options={'permissions': [('can_change_bookshop', 'can change bookshop')]},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'permissions': [('can_change_dish', 'can change dish')]},
        ),
        migrations.AlterModelOptions(
            name='electronicsshop',
            options={'permissions': [('can_change_electronicsshop', 'can change electronicsshop')]},
        ),
        migrations.AlterModelOptions(
            name='flowershop',
            options={'permissions': [('can_change_flowershop', 'can change flowershop')]},
        ),
        migrations.RemoveField(
            model_name='bookshop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookshop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='electronicsshop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='electronicsshop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='flowershop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flowershop',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='ModelList',
        ),
        migrations.DeleteModel(
            name='UserModelPermission',
        ),
    ]
