# Generated by Django 4.2.3 on 2023-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0004_modellist_remove_dish_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='book_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='electronicsshop',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='flowershop',
            name='flower_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
