# Generated by Django 4.2.3 on 2023-08-06 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0005_alter_bookshop_book_title_alter_dish_dish_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('user', 'user'), ('subuser', 'subuser')], default='Superuser', max_length=50),
        ),
        migrations.DeleteModel(
            name='SubUser',
        ),
    ]
