# Generated by Django 4.2.3 on 2023-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0006_user_created_by_alter_user_role_delete_subuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellist',
            name='model_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
