# Generated by Django 4.2.3 on 2023-08-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0007_alter_modellist_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodelpermission',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='modellist',
            name='model_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usermodelpermission',
            unique_together={('user_id', 'model_id')},
        ),
    ]
