# Generated by Django 4.2.3 on 2023-08-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0008_rename_user_usermodelpermission_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodelpermission',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='usermodelpermission',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usermodelpermission',
            unique_together={('user', 'model')},
        ),
    ]
